#index:
#    path: /
#    controller: App\Controller\DefaultController::index

search_customer:
    path: /searchCustomer
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
      template: 'Customer/search.html.twig'

search_car:
  path: /searchCar
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: 'Car/search.html.twig'

search_worksheet:
  path: /searchWorksheet
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: 'Worksheet/search.html.twig'
